# Generated by Django 4.1.5 on 2023-04-18 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
