# Generated by Django 4.1.5 on 2023-04-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_recipe_user_rating"
            ),
        ),
    ]
