# Generated by Django 4.1.5 on 2023-04-10 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
    ]
