# Generated by Django 4.1.5 on 2023-04-11 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_options_remove_account_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
    ]
