# Generated by Django 4.1.5 on 2023-04-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipe_user"),
        ("accounts", "0003_remove_account_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="recipes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
    ]
