# Generated by Django 4.1.5 on 2023-04-12 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="recipes",
        ),
    ]
