# Generated by Django 4.1.5 on 2023-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
