# Generated by Django 4.1.5 on 2023-04-16 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_recipe_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="rating",
        ),
    ]
