# Generated by Django 4.1.5 on 2023-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_remove_recipe_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
